### PR TITLE
Setup actions

### PR DESCRIPTION
**Pull request by mj0nez**

### CODE REVIEW

**Comment by nerdoc** [comment]
This is great. I have never worked with that in Github, but I can only second that. Is there a way to auto-fix "black" format errors (i.e. just black them automatically by bot)? The only check that failed was that.

**Comment by nerdoc** [comment]
One thing: There is [one issue](https://github.com/nerdocs/pydifact/issues/36) and a [PR](https://github.com/nerdocs/pydifact/pull/35) by @theangryangel that kept me cutting the old braids, meaning Python 3.5. compatibility - which is due now. He was stuck in Py3.5 in a project, and could not change that dependency.
@theangryangel, What do you say about that? Can we?

**Comment by theangryangel** [comment]
> @theangryangel, What do you say about that? Can we?

Go for it 👍

**Comment by mj0nez** [comment]
> Is there a way to auto-fix "black" format errors (i.e. just black them automatically by bot)?

I have not used one yet, but [this](https://peterevans.dev/posts/github-actions-how-to-automate-code-formatting-in-pull-requests/) may work.

A more simple and IMO cleaner solution would be to deploy black as just another checking-stage and leave the actual formatting and code changes to the contributors.

**Pull request merged**
